### PR TITLE
Removed OR clause for non-load commanding

### PR DESCRIPTION
**Pull request by richardjedgar**
I have deleted the OR clause for non-load commanding, as in the other thermal model check tools.

### CODE REVIEW

**Comment by jzuhone** [comment]
Might be worth running this on today's load manually to make sure nothing weird crops up.

**Comment by Gregg140** [comment]
It needs to be re-run agains the load that revealed the problem.

**Comment by richardjedgar** [comment]
Perhaps when the others are done we can do one run to verify?

**Comment by jzuhone** [comment]
@Gregg140 sure, but as we said before the issue won't crop up again because now the commanded states database is up to date.

**Comment by jeanconn** [comment]
Though if you want to modify the db handle for testing, I should have a
backup of the sqlite version of the database at the time of the problem.

**Comment by jeanconn** [comment]
My only concern is that there might be legitimate overlap between products in review and the onboard loads.  Theoretically, the cmd_states database should be able to answer that question, but I haven't done the exercise.

**Comment by richardjedgar** [comment]
Testing against vanilla load MAR1317A showed no significant differences. Initial conditions and time covered in validation were slightly different because they depend on when the model was run.

**Comment by Gregg140** [comment]
We are not aware of an overlap in the commands that ACIS cares about between the Broken load and the load under review. This ignores the 3 minute negative delta time ACA reset command which we ignore.

Can you elaborate on the scenario you have in mind?

**Comment by jeanconn** [comment]
On Mon, Mar 6, 2017 at 2:24 PM, Gregg140 <notifications@github.com> wrote:

> We are not aware of an overlap in the commands that ACIS cares about
> between the Broken load and the load under review. This ignores the 3
> minute negative delta time ACA reset command which we ignore.
>
> Can you elaborate on the scenario you have in mind?
>
​No.

My concern is solely based on Tom's commit comment "​ The issue had been
that just filtering cmds on time (before the first backstop cmd) was
dropping some commands from the previous load segment because of the
frequent
3 minute overlap."  I would need to actually do the exercise and check for
command overlap to see what this "frequent 3 minute overlap" is and to see
if ACIS commands in separate products have previously overlapped in a way
that might be significant.

**Comment by Gregg140** [comment]
I think the 3 minute overlap is the ACA camera command that is almost always at the start of the new load and whose time of execution is always 3 minutes before the start of the new load.

ACIS Ops ignores that command for processing purposes.

**Comment by richardjedgar** [comment]
I have tested this with four loads: FEB2017, FEB2717, MAR0617, and MAR1317, and the prediction and validation plots looked identical.

**Comment by richardjedgar** [comment]
The temperature.dat predictions files are also identical for each of the 4 loads, between the released version and the one in this pull request.

**Comment by richardjedgar** [comment]
I added the MAR0817B load to the test list, and again the new code and the released version produce identical results. Since SCS-107 ran to interrupt the MAR0617 load, the model picked up the transition.

**Comment by jeanconn** [comment]
> I think the 3 minute overlap is the ACA camera command that is almost always at the start of the new load and whose time of execution is always 3 minutes before the start of the new load.
> 
> ACIS Ops ignores that command for processing purposes.

I don't think any ACA commands are parsed by Chandra.cmd_states, so it seems unlikely that Tom would have left in some overlap to include them.

**Comment by jeanconn** [comment]
Looking at the end of FEB2017A I see three ACISPKT commands that are technically after the start of the backstop of FEB2717A.  Is that commanding just redundant?  I suppose this *is* due to the AOACRSTD which ends up being the first command in FEB2717A backstop... as the beginning of the backstop for the purpose of this code change is (bs_cmds[0]['time']) where I believe bs_cmds includes all commands ... not just the relevant ones.

**Comment by Gregg140** [comment]
I'm looking at that very interface now - FEB 20 and FEB 27.  I think the model code messes up the sequence of commands because of the negative time delta ACA command. I'm checking it out and characterizing what happens.

BTW none of this has to do with the "None clause".  It's independent of that.

**Comment by jeanconn** [comment]
"BTW none of this has to do with the "None clause". It's independent of that."

Not sure what you mean by that.  My understanding is that, before the change suggested in this PR, these 3 commands (which are after backstop start and have timeline_id not None) would be used in the computed states in the model but that after the change they would not (as they are after backstop start).

**Comment by Gregg140** [comment]
I'm saying that this line of code:

db_cmds = [x for x in db_cmds if x['time'] < bs_cmds[0]['time'] ]


screws up the sequence of commands even though the NONE clause has been removed.  That the screw up I'm seeing is independent of the None clause.

Let me finish the investigation and characterize what happens and then you can see what I mean.

**Comment by jeanconn** [comment]
I was still a little confused about the commands at the end of FEB20.

**Comment by jzuhone** [comment]
@jeanconn right, @Gregg140 merged this in by accident. he thought he was merging the JSON file update PR.

Not sure  how to proceed from here--should we try undoing the merge?

**Comment by jeanconn** [comment]
I haven't done it much, but I think the revert/undo is fine.

If that doesn't work, you can rebase a local master and force push.  This was a small PR anyway so I don't see it as being a big deal either way.

**Comment by jzuhone** [comment]
@jeanconn, I've rebased on the master as of the merge of the new PSMC model and force pushed, so everything should be ok now. I also updated the version and tagged a new release. @richardjedgar will have to re-submit the changes here as a new PR.

**Pull request merged**
