### PR TITLE
Updated fits for 2019/2020

### PR DESCRIPTION
**Pull request by jazan12**
With normalized solar constants, and same as in SOT upload.

### CODE REVIEW

**Comment by jeanconn** [comment]
Is this planned for release this week?

**Comment by jazan12** [comment]
It depends on what happens with the proposal for json update fast-tracking at FDB, but if that is greenlit then yes that would be the plan.

**Comment by jeanconn** [comment]
I think this should go for LR review this week then and if the json psmc model on the matlab side doesn't get approved we could hold on promotion.  Either way, it would be good to just approve, merge, github release this now (now being no rush but it sounds like we aren't looking at any changes to the PR so no reason to wait).

**Comment by jazan12** [comment]
Thanks for the advice on that front Jean.  Is Matt the power that can merge it up the food chain?

**Comment by jeanconn** [comment]
Thanks @jazan12!  My understanding of process is that for the version of the model here in psmc_check ACIS can sign off and approve the PR (verification is really just that it matches the one in chandra_models update).  Then psmc_check (1.3.0?) should go to LR as an ACIS load review tool change (even though the json file update is not a code change).  And at whatever time it makes sense to promote, @javierggt or I will install updated psmc_check in ska3/flight .

**Comment by jzuhone** [comment]
I'm going to merge and tag this now.

**Comment by jzuhone** [comment]
@jeanconn I tagged this: 

https://github.com/acisops/psmc_check/releases/tag/1.3.0

**Comment by jazan12** [comment]
Thanks John!

**Pull request merged**
