### PR TITLE
Roll-aware PSMC model, fit to heater-on&off data; Version 0.3->0.4

### PR DESCRIPTION
**Pull request by richardjedgar**
ACIS Ops please review these changes...

I've added code to psmc_check.py to make it roll aware.

Tom and I have come up with a decent-fitting model, which is rather different in most details from the previous one. This is essentially his fit5_psmc_spec.json file, with minor changes of mine.

I have bumped the VERSION number from 0.3 to 0.4.

Comparison between the old and new PSMC models can be done on recent weeks by looking at these web pages:

old: http://cxc.cfa.harvard.edu/acis/PSMC_thermPredic/APR1816/oflsa/
new: http://cxc.cfa.harvard.edu/acis/tmp/psmc_APR1816/index.html

old: http://cxc.cfa.harvard.edu/acis/PSMC_thermPredic/APR0416/oflsc/
new: http://cxc.cfa.harvard.edu/acis/tmp/psmc_APR0416/index.html

The Detector Housing Heater was turned on on 2015:223. To assess how much of an overprediction we should expect from the present model (0.4) if we turn the heater off again, I've plotted residuals in guifit (data minus model vs. data) for two time periods, using this model: [a] the 400 days prior to turning the heater on in 2015, and [b] the 245 days after turning the heater on. In the hot case, it appears that the model overpredicts the heater-off case by 1 to 2 degrees C, which we can live with until such time as there's enough heater-off data to recalibrate if need be.

Before the heater was turned off: 
guifit_5b_2015_222_400days

After the heater was turned on:
guifit_5b_2016_102_245days

### CODE REVIEW

**Comment by jzuhone** [comment]
This looks good to me.

**Comment by richardjedgar** [comment]
As further "it does what we expect" validation, here are two plots for times with a large negative value of off-nominal rolls. On day 2015:351-352, and again on 2015:353-354, the off-nominal roll angle were -18 and -16 degrees. We expect, since the PSMC is physically on the +Y side of the ISIM, that this will be a hot attitude for the PSMC. Indeed, the currently baselined model underpredicts at these times:

baseline_1pdeaat_valid

while the new model proposed here does a much better job of matching the data:

fit5b_1pdeaat_valid

Other effects (mostly due to refitting the parameters) are responsible for the model improvements after day 2015:361 or so.

**Comment by jzuhone** [comment]
It's occurred to me as I was looking over this code that it takes the value of 1PIN1AT as an input. Given how badly it has been behaving recently, is this still something we want? Just wondering.

**Comment by pplucinsky** [comment]
hi Dick,

   Very nice.  The new model also mostly corrects the over-predictions on
DOY 361 and 364.  Can that be explained by off-nominal roll also ?  Or is
something else going on ?

thanks,
Paul

On Wed, May 4, 2016 at 3:22 PM, richardjedgar <notifications@github.com>
wrote:

> As further "it does what we expect" validation, here are two plots for
> times with a large negative value of off-nominal rolls. On day
> 2015:351-352, and again on 2015:353-354, the off-nominal roll angle were
> -18 and -16 degrees. We expect, since the PSMC is physically on the +Y side
> of the ISIM, that this will be a hot attitude for the PSMC. Indeed, the
> currently baselined model underpredicts at these times:
>
> [image: baseline_1pdeaat_valid]
> <https://cloud.githubusercontent.com/assets/9807359/15026268/96a3de32-120b-11e6-96a4-fb6afdc9b7fc.png>
>
> while the new model proposed here does a much better job of matching the
> data:
>
> [image: fit5b_1pdeaat_valid]
> <https://cloud.githubusercontent.com/assets/9807359/15026283/b135ff1e-120b-11e6-9438-e199a310cf36.png>
>
> Other effects (mostly due to refitting the parameters) are responsible for
> the model improvements after day 2015:361 or so.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/acisops/psmc_check/pull/1#issuecomment-216973012>
>



-- 
===================================================
Paul P. Plucinsky                             Harvard-Smithsonian Center
plucinsky@cfa.harvard.edu                for Astrophysics, MS 3
Phone:  617-496-7726                        60 Garden Street
FAX:    617-495-7356                        Cambridge, MA  02138  USA
Cellphone: 617-721-4366                   Pager email:6177214366@vtext.com

**Comment by pplucinsky** [comment]
hmmmm, I hope 1PIN1AT is not being used by this model.  How could it
produce sensible results if 1PIN1AT is pegged at +71.8 C ?

On Fri, May 6, 2016 at 10:45 AM, John ZuHone <notifications@github.com>
wrote:

> It's occurred to me as I was looking over this code that it takes the
> value of 1PIN1AT as an input. Given how badly it has been behaving
> recently, is this still something we want? Just wondering.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/acisops/psmc_check/pull/1#issuecomment-217460196>
>



-- 
===================================================
Paul P. Plucinsky                             Harvard-Smithsonian Center
plucinsky@cfa.harvard.edu                for Astrophysics, MS 3
Phone:  617-496-7726                        60 Garden Street
FAX:    617-495-7356                        Cambridge, MA  02138  USA
Cellphone: 617-721-4366                   Pager email:6177214366@vtext.com

**Comment by richardjedgar** [comment]
The roll angle is very close to nominal for days 361 & 364, so there's some other improvement in the model that makes that happen.

The model has a dummy node called "1PIN1AT" but in the fitting nothing is done to attempt to get that node to match the data from the (now broken) thermistor. It's not clear to me what, if anything, is done with the telemetry for that MSID.

**Comment by jzuhone** [comment]
I'm going to merge this now but I will have a look at what is being done (if anything) with 1PIN1AT.

**Pull request merged**
